export const MEDICAL_SPECIALTIES = [
  { value: 'anaesthesiology', en: 'Anaesthesiology', es: 'Anestesiología' },
  { value: 'cardiology', en: 'Cardiology', es: 'Cardiología' },
  { value: 'chemical-pathology', en: 'Chemical Pathology', es: 'Patología Química' },
  { value: 'clinical-genetics', en: 'Clinical Genetics', es: 'Genética Clínica' },
  { value: 'clinical-pharmacology', en: 'Clinical Pharmacology', es: 'Farmacología Clínica' },
  { value: 'dermatology', en: 'Dermatology', es: 'Dermatología' },
  { value: 'emergency-medicine', en: 'Emergency Medicine', es: 'Medicina de Urgencias' },
  { value: 'endocrinology', en: 'Endocrinology', es: 'Endocrinología' },
  { value: 'gastroenterology', en: 'Gastroenterology', es: 'Gastroenterología' },
  { value: 'general-internal-medicine', en: 'General Internal Medicine', es: 'Medicina Interna General' },
  { value: 'general-practice', en: 'General Practice', es: 'Medicina General' },
  { value: 'general-surgery', en: 'General Surgery', es: 'Cirugía General' },
  { value: 'genito-urinary-medicine', en: 'Genito-Urinary Medicine', es: 'Medicina Genitourinaria' },
  { value: 'geriatric-medicine', en: 'Geriatric Medicine', es: 'Geriatría' },
  { value: 'haematology', en: 'Haematology', es: 'Hematología' },
  { value: 'histopathology', en: 'Histopathology', es: 'Histopatología' },
  { value: 'immunology', en: 'Immunology', es: 'Inmunología' },
  { value: 'infectious-diseases', en: 'Infectious Diseases', es: 'Enfermedades Infecciosas' },
  { value: 'internal-medicine', en: 'Internal Medicine', es: 'Medicina Interna' },
  { value: 'medical-oncology', en: 'Medical Oncology', es: 'Oncología Médica' },
  { value: 'microbiology', en: 'Microbiology', es: 'Microbiología' },
  { value: 'neonatology', en: 'Neonatology', es: 'Neonatología' },
  { value: 'nephrology', en: 'Nephrology', es: 'Nefrología' },
  { value: 'neurology', en: 'Neurology', es: 'Neurología' },
  { value: 'neuropathology', en: 'Neuropathology', es: 'Neuropatología' },
  { value: 'neurosurgery', en: 'Neurosurgery', es: 'Neurocirugía' },
  { value: 'obstetrics-gynaecology', en: 'Obstetrics & Gynaecology', es: 'Obstetricia y Ginecología' },
  { value: 'occupational-medicine', en: 'Occupational Medicine', es: 'Medicina del Trabajo' },
  { value: 'oncology', en: 'Oncology', es: 'Oncología' },
  { value: 'ophthalmology', en: 'Ophthalmology', es: 'Oftalmología' },
  { value: 'oral-maxillofacial-surgery', en: 'Oral & Maxillofacial Surgery', es: 'Cirugía Oral y Maxilofacial' },
  { value: 'orthopaedics', en: 'Orthopaedics', es: 'Traumatología' },
  { value: 'otolaryngology', en: 'Otolaryngology (ENT)', es: 'Otorrinolaringología' },
  { value: 'paediatric-surgery', en: 'Paediatric Surgery', es: 'Cirugía Pediátrica' },
  { value: 'paediatrics', en: 'Paediatrics', es: 'Pediatría' },
  { value: 'palliative-medicine', en: 'Palliative Medicine', es: 'Medicina Paliativa' },
  { value: 'pathology', en: 'Pathology', es: 'Patología' },
  { value: 'pharmaceutical-medicine', en: 'Pharmaceutical Medicine', es: 'Medicina Farmacéutica' },
  { value: 'plastic-surgery', en: 'Plastic Surgery', es: 'Cirugía Plástica' },
  { value: 'psychiatry', en: 'Psychiatry', es: 'Psiquiatría' },
  { value: 'public-health-medicine', en: 'Public Health Medicine', es: 'Salud Pública' },
  { value: 'radiation-oncology', en: 'Radiation Oncology', es: 'Oncología Radioterápica' },
  { value: 'radiology', en: 'Radiology', es: 'Radiología' },
  { value: 'rehabilitation-medicine', en: 'Rehabilitation Medicine', es: 'Medicina de Rehabilitación' },
  { value: 'respiratory-medicine', en: 'Respiratory Medicine', es: 'Neumología' },
  { value: 'rheumatology', en: 'Rheumatology', es: 'Reumatología' },
  { value: 'sports-exercise-medicine', en: 'Sports & Exercise Medicine', es: 'Medicina Deportiva' },
  { value: 'tropical-medicine', en: 'Tropical Medicine', es: 'Medicina Tropical' },
  { value: 'urology', en: 'Urology', es: 'Urología' },
  { value: 'vascular-surgery', en: 'Vascular Surgery', es: 'Cirugía Vascular' },
] as const

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number]['value']
